# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_foodtypes_goods_mainshow_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
    ]
