# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-03 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20181103_1706'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='goods',
            table='axf_goods',
        ),
    ]
